version: '3'
services:

  # PHP Service
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: marcospacheco/php-8.1
    container_name: app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.docker/php/custom.php.ini:/usr/local/etc/php/conf.d/custom.php.ini

    networks:
      - cadastro_fornecedor
      
  # Nginx Service cadastro_fornecedor
  cadastro_fornecedor:
    image: nginx:alpine
    container_name: cadastro_fornecedor
    restart: always
    tty: true
    ports:
      - "81:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - cadastro_fornecedor
      - mysql

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    tty: true
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - cadastro_fornecedor
      - mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - mysql

#Docker Networks
networks:
  cadastro_fornecedor:
    driver: bridge
  mysql:
    driver: bridge
